# rubenmoor/ghc-base

FROM debian:jessie

MAINTAINER Ruben Moor <ruben.moor@gmail.com>

RUN apt-get update && apt-get install -q -y \
    bzip2 \
    curl \
    gcc \
    git \
    libgmp-dev \
    make \
    zlib1g-dev \
    dh-autoreconf
